[VALIDATORS]
public_key = "nHUFFKsfSYR1T314mJpFoxztThe6f8EqZmmpUWpWfCUuzQcd8uKV"
validation_public_key = "nHUFFKsfSYR1T314mJpFoxztThe6f8EqZmmpUWpWfCUuzQcd8uKV"
domain = "texasblockchain.org"

[CONTACT]
name = "Texas Blockchain"
country = 'US"

[METADATA]
modified = "2025-04-05"

